<?php
/*
    This file is part of EnvoiMoinsCher's shipping plugin for Magento.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/** 
 * @category    Boxtale
 * @package     Boxtale_Envoimoinscher
 * @copyright   Copyright (c) 2011 EnvoiMoinsCher.com
 * @author 	    EnvoiMoinsCher (http://www.envoimoinscher.com)
 * @license     http://www.gnu.org/licenses  GNU Lesser General Public License (LGPL)
 */
?>
<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td><h3>Editer une offre de transport</h3></td>
      <td class="form-buttons"><?php echo $this->getButtonsHtml(); ?></td>
    </tr>
  </table>
</div>

<div>
Seules les offres de transport que vous avez sélectionnées sur la page de configuration du module apparaissent ici. Vous pouvez les personnaliser (libellé du nom, etc.) en cliquant sur "Editer".
</div>