<?php
/**
 * LaPoste_SoColissimoSimplicite
 *
 * @category  LaPoste
 * @package   LaPoste_SoColissimoSimplicite
 * @copyright Copyright (c) 2010 La Poste
 * @author    Smile (http://www.smile.fr)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
?>
<?php $_helper = $this->helper('socolissimosimplicite'); ?>

<h1><?php echo $_helper->__('Une erreur technique a été rencontrée') ?></h1>

<p><?php echo $_helper->__('Merci de soumettre votre commande ultérieurement') ?></p>
