<?php
/*
    This file is part of EnvoiMoinsCher's shipping plugin for Magento.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/** 
 * @category    Boxtale
 * @package     Boxtale_Envoimoinscher
 * @copyright   Copyright (c) 2011 EnvoiMoinsCher.com
 * @author 	    EnvoiMoinsCher (http://www.envoimoinscher.com)
 * @license     http://www.gnu.org/licenses  GNU Lesser General Public License (LGPL)
 */
?>
<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td><h3>Aide</h3></td>
    </tr>
  </table>
</div>
<div style="clear:both;">
<p>Pour installer et configurer le module, suivez les instructions de <a href="http://www.envoimoinscher.com/api/download/user_guide-emc_magento.pdf" target="_blank">la documentation</a>.</p>
<p>N'hésitez pas à nous contacter si vous rencontrez un problème et ne trouvez pas la réponse à vos
questions :</p>
</div>
<div style="float:left; margin-right:40px;">
  <ul class="messages biggerFont"><li class="notice-msg">
    <p><b>Contacts service client :</b></p>
    <ul>
      <li class="withStyleSquare"><a href="mailto:contact@envoimoinscher.com">contact@envoimoinscher.com</a> ou
      <a href="mailto:informationAPI@envoimoinscher.com">informationAPI@envoimoinscher.com</a></li>
      <li class="withStyleSquare">par téléphone au +33 (0)1 75 77 37 97</li>
    </ul>
  </li></ul>
</div>
<div style="float:left;">
  <ul class="messages biggerFont"><li class="notice-msg">
    <p><b>Contacts techniques :</b></p>
    <ul>
      <li class="withStyleSquare"><a href="mailto:dev@boxtale.com">dev@boxtale.com</a></li>
      <li class="withStyleSquare">par téléphone au +33 (0)1 75 77 37 96</li>
      <li class="withStyleSquare">via skype : dev_envoimoinscher</li>
    </ul>
  </li></ul>
</div>