<?php
/*
    This file is part of EnvoiMoinsCher's shipping plugin for Magento.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/** 
 * @category    Boxtale
 * @package     Boxtale_Envoimoinscher
 * @copyright   Copyright (c) 2011 EnvoiMoinsCher.com
 * @author 	    EnvoiMoinsCher (http://www.envoimoinscher.com)
 * @license     http://www.gnu.org/licenses  GNU Lesser General Public License (LGPL)
 */
?>
<script type="text/javascript">
var baseUrl = '<?php echo Mage::getBaseUrl(); ?>';
var noLabels = new Array();
var reqs = new Array();
var tries = 0;
var labelsToDo = 0;
Event.observe(window, 'load', function() {
  orderLabelsToDo();
  doLabelRequest(0);
});

function orderLabelsToDo()
{
  noLabels = new Array();
  var inputs = document.getElementsByName('bord[]');
  for(var i=0; i < inputs.length; i++)
  {
    noLabels[i] = inputs[i].value;
  }
  labelsToDo = inputs.length;
}
var t = 10000;
// var t = 1000;
function doLabelRequest(index)
{
  if(typeof noLabels[index] == "undefined" && noLabels.length > 0 && index >= labelsToDo) 
  {
    orderLabelsToDo();
    setTimeout("doLabelRequest(0)", t);
    return;
  }
  else if(typeof noLabels[index] == "undefined" && noLabels.length > 0 && index < labelsToDo) 
  {
    index = index + 1;
    setTimeout("doLabelRequest("+index+")", t);
    return;
  }
  else if(typeof noLabels[index] == "undefined")
  {
    return;
  }
  new Ajax.Request("<?php echo Mage::getUrl('envoimoinscher/labels/check', array());?>",
  {
    evalScripts : true,
    parameters : {orderId : noLabels[index]},
    onSuccess : function(rsp) 
    {
      var res = rsp.responseText.evalJSON();
      tries = 0;
      if(res.error == 0)
      {
        if(""+res.labelAvailable == "1")
        {
          // put label's url into orders table
          $("info"+noLabels[index]).remove();
          $("labelLink"+noLabels[index]).setStyle({display : 'block'}); 
          noLabels.splice(index, 1);
          labelsToDo--;
          if(labelsToDo == 0) return;
        }
        var o = index + 1;
        setTimeout("doLabelRequest("+o+")", t);
      }
      else if(res.error == 1)
      {
alert("Une erreur s'est produite dans la requête.");
        setTimeout("doLabelRequest("+index+")", t);
      }
    },
    onFailure: function()
    {
alert("Une erreur s'est produite. Veuillez réessayer.");
      setTimeout("doLabelRequest("+index+")", t);
    }
  });
}
</script>

<p><b>Les commandes ci-dessous sont celles dont vous avez déjà déclenché l'ordre d'envoi.
<br />Pour télécharger les bordereaux de plusieurs de vos envois, cochez les cases situées en-dessous des numéros de commande puis cliquez sur "Télécharger les bordereaux"</b></p>